### ISSUE TITLE
Terraform Random Bucket Name

### ISSUE THREAD

**Issue by mhasabal** [mhasabal/terraform-beginner-bootcamp-2023#13]
### Task List:
- [ ] **Explore the Terraform Registry.**
- [ ] **Install the Terraform Random Provider:**
- [ ] ** Run Terraform Init**
- [ ] **Output the Random Bucket Name to Outputs**
